export const NETWORK = {
  TICK_RATE: 60,
  TICK_INTERVAL_MS: 1000 / 60,
  CLIENT_SEND_RATE: 60,
  INTERPOLATION_DELAY_MS: 100,
  MAX_INPUT_BUFFER_SIZE: 64,
  SNAPSHOT_BUFFER_SIZE: 32,
  DEFAULT_PORT: 3001,
} as const;
